### ISSUE TITLE
Unable to Publish

### ISSUE THREAD

**Issue by CreativeWolf** [kevin-kibet/laravel-ejabberd#1]
Heya,

While using

`./artisan vendor:publish --provider="Ejabberd\Providers\EjabberdServiceProvider"`

It returned error message:

`Can't locate path: </var/www/html/simple-chat-app/vendor/kevin-kibet/laravel-ejabberd/src/Providers/../config/ejabberd.php>`

Had to change line 41 from 
`return __DIR__ . '/../config/ejabberd.php';`
to 
`return  __DIR__ . '/../../config/ejabberd.php';`

After that it returned the following:

```
 ./artisan vendor:publish --provider="Ejabberd\Providers\EjabberdServiceProvider"
Copied File [/vendor/kevin-kibet/laravel-ejabberd/config/ejabberd.php] To [/config/ejabberd.php]
Publishing complete. ./artisan vendor:publish --provider="Ejabberd\Providers\EjabberdServiceProvider"
Copied File [/vendor/kevin-kibet/laravel-ejabberd/config/ejabberd.php] To [/config/ejabberd.php]
Publishing complete.
```
Just wanted to confirm if that's fine to do.

Cheers

**Comment by kevin-kibet** [comment]
Thanks. Got it fixed.
